name: Check AuthZ Model

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        run: npm ci
      - name: Check
        run: npm run test